[project]
authors = ["Nodar Gogoberidze <gnodar01@gmail.com>"]
channels = ["fastai", "conda-forge"]
name = "nbdev-exp"
platforms = ["osx-64"]
version = "0.1.0"

[tasks]
sync_nb = "jupytext --sync \"$PIXI_PROJECT_ROOT/nbs/*.ipynb\""
sync_py = "jupytext --sync \"$PIXI_PROJECT_ROOT/jpt/*.py\""
launch_jl = "jupyter lab"
launch_preview = "nbdev_preview"
clean = "nbdev_clean && jupytext --sync \"PIXI_PROJECT_ROOT/jpt/*.py\" && rm -f \"$PIXI_PROJECT_ROOT/.jupyter_ystore.db\""
test = "nbdev_test"
# could in theory have watchexec automate this
tangle = "nbdev_export"
readme = "nbdev_readme"

[dependencies]
python = "3.10.*"
jupyterlab = ">=4.4.0,<5"

[pypi-dependencies]
nbdev-exp = { path = ".", extras = ["dev"], editable = true }
nbdev = ">=2.4.2, <3"
jupytext = ">=1.17.0, <2"
ipyflow = ">=0.0.209, <0.0.210"
jupyter-collaboration = ">=4.0.1, <5"
jldracula = ">=0.2.0, <0.3"
