[project]
authors = ["Nodar Gogoberidze <gnodar01@gmail.com>"]
channels = ["fastai", "conda-forge"]
name = "nbdev-exp"
platforms = ["osx-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.10.*"
jupyterlab = ">=4.4.0,<5"

[pypi-dependencies]
nbdev-exp = { path = ".", extras = ["dev"], editable = true }
nbdev = ">=2.4.2, <3"
jupytext = ">=1.17.0, <2"
